# Puerto donde corre tu backend
server.port=9090

# Conexión a MySQL (AHORA con allowPublicKeyRetrieval)
spring.datasource.url=jdbc:mysql://localhost:3306/tiendacoco?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Si quieres quitar la advertencia puedes hacer default (no es estrictamente necesario):
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
# Tiempo de expiración del token (en ms): 1 hora = 3600000 ms
jwt.expirationMs=3600000
jwt.secret=MiSuperSecretoQueDebeSerLargo1234567890
